# Generated by Django 4.0.5 on 2022-06-25 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='product_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='useful_or_not',
            field=models.CharField(choices=[('U', 'useful'), ('N', 'useless')], max_length=1),
        ),
    ]
