# Generated by Django 4.0.5 on 2022-06-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='myuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='girocard',
            old_name='myuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='myuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='myuser',
            new_name='user',
        ),
    ]
