# Generated by Django 4.0.6 on 2022-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
