# Generated by Django 4.0.5 on 2022-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingcart', '0002_rename_myuser_creditcard_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girocard',
            name='iban',
            field=models.CharField(max_length=27, primary_key=True, serialize=False),
        ),
    ]
