# Generated by Django 4.0.5 on 2022-07-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingcart', '0003_alter_girocard_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
