# Generated by Django 4.0.5 on 2022-06-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profilepicture',
            new_name='profile_picture',
        ),
    ]
